# Site settings
title: "Jaime Caballero, front-end architect based in London - OOCSS, Sass, BEM, "
email: me@jaicab.com
description: "Front-end architect based in London"
baseurl: ""
url: "http://jaicab.com"
username: "jaicab"
twitter: "jaicab_"

# Build settings
markdown: kramdown
permalink: pretty
exclude: [README.md, css/*.scss]
highlighter: pygments

# Pagination
paginate: 10