# Site settings
title: Jaime Caballero
email: contact@jaicab.com
description: "Freelance front-end architect based in Spain"
intro: "Jaime Caballero is a front-end architect, designer and developer from Spain."
baseurl: ""
url: "http://jaicab.com"
username: "jaicab"
twitter: "jaicab_"

# Build settings
markdown: kramdown
permalink: pretty
exclude: [README.md, css/*.scss]
highlighter: pygments

# Pagination
paginate: 10