# Site data
title: "Jaime Caballero"
email: me@jaicab.com
fullname: "Jaime Caballero"
description: "Frontend architect based in London"
baseurl: ""
url: "https://jaicab.com"
enforce_ssl: "http://jaicab.com"
username: "jaicab"
twitter: "jaicab_"
instagram: "jai_cab"
repository: jaicab/jaicab.github.io
timezone: Europe/London

navigation:
  - title: Articles
    url: /articles/
    desc: "Read articles about Sass, web performance and frontend techniques"
  - title: Projects
    url: /projects/
    desc: "Projects I have built in my own time"
  - title: Work
    url: /work/
    desc: "Case studies of websites I have built during my career"
  - title: About
    url: /about/
    desc: "My personal profile, my hobbies and tips for developers"

collections:
  - projects
  - work

  # Default front-matter
defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: post
      schema: BlogPosting
  - scope:
      path: ""
    values:
      image: "/apple-touch-icon.png"

# Build settings
permalink: pretty
exclude:
  - README.md
  - _src/
  - node_modules/
  - Gruntfile.js
  - package.json
  - vendor

# Pagination
paginate: 5
paginate_path: "/articles/page:num/"

#Gems
plugins:
  - jekyll-redirect-from
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-feed
