# Site settings
title: "Frontend architect based in London | Jaime Caballero"
email: me@jaicab.com
description: "Frontend architect based in London"
baseurl: ""
url: "https://jaicab.com"
enforce_ssl: "http://jaicab.com"
username: "jaicab"
twitter: "jaicab_"

# Build settings
permalink: pretty
exclude:
  - README.md
  - _src/
  - node_modules/
  - Gruntfile.js
  - package.json

# Pagination
paginate: 5


#Gems
gems:
  - jekyll-redirect-from
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-feed