
# Site data
title: "Frontend architect based in London | Jaime Caballero"
email: me@jaicab.com
fullname: "Jaime Caballero"
description: "Frontend architect based in London"
baseurl: ""
url: "https://jaicab.com"
enforce_ssl: "http://jaicab.com"
username: "jaicab"
twitter: "jaicab_"

navigation:
 - title: Articles
   url: /articles/
 - title: Projects
   url: /projects/
 - title: Work
   url: /work/
 - title: About
   url: /about/


# Build settings
permalink: pretty
exclude:
  - README.md
  - _src/
  - node_modules/
  - Gruntfile.js
  - package.json

# Pagination
paginate: 5

#Gems
gems:
  - jekyll-redirect-from
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-feed