# Site settings
title: "Jaime Caballero, front-end architect from Spain - OOCSS, Sass, BEM, "
email: contact@jaicab.com
description: "Freelance front-end architect based in Spain"
baseurl: ""
url: "http://jaicab.com"
username: "jaicab"
twitter: "jaicab_"

# Build settings
markdown: kramdown
permalink: pretty
exclude: [README.md, css/*.scss]
highlighter: pygments

# Pagination
paginate: 10