# Site settings
title: "Frontend architect based in London | Jaime Caballero"
email: me@jaicab.com
description: "Frontend architect based in London"
baseurl: ""
url: "https://jaicab.com"
enforce_ssl: "http://jaicab.com"
username: "jaicab"
twitter: "jaicab_"

# Build settings
markdown: kramdown
permalink: pretty
exclude: [README.md, css/*.scss]

# Pagination
paginate: 5


#Gems
gems:
  - jekyll-redirect-from
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-feed


#Include
include: [
  '.well-known'
]