# Site settings
title: "Frontend architect based in London | Jaime Caballero"
email: me@jaicab.com
description: "Frontend architect based in London"
baseurl: ""
url: "https://jaicab.com"
username: "jaicab"
twitter: "jaicab_"

# Build settings
markdown: kramdown
permalink: pretty
exclude: [README.md, css/*.scss]
highlighter: pygments

# Pagination
paginate: 10

#Gems
gems:
  - jekyll-redirect-from